

### 
POST http://localhost:5000/api/discount/
Content-Type: application/json

{
    "code": "RUNNER15",
    "description": "Giảm 15% cho các sản phẩm chạy bộ",
    "discountType": "percentage",
    "amount": 15,
    "validFrom": "2025-03-01",
    "validUntil": "2025-03-31",
    "applicableProducts": [],
    "applicableCategories": ["67dd5478f11922ce575ccb17"]
}

###
GET http://localhost:5000/api/discount/


