POST http://localhost:5000/api/category
Content-Type: application/json

 {
        "name": "",
        "description": ""
    }
###
GET http://localhost:5000/api/category

### 
DELETE http://localhost:5000/api/category/67dd25e8e8658788204f3735

###
PUT http://localhost:5000/api/category/67dd272c1d999ea6a0ff0005
Content-Type: application/json

{
    "description":"Giay the thao"
}

###
GET http://localhost:5000/api/product

###
POST http://localhost:5000/api/product
Content-Type: application/json

{
    
}